// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: ssn/scanner/v1/scanner_internal.proto

package scanner

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// Validate checks the field values on InternalScanResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *InternalScanResponse) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetScanResponse()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return InternalScanResponseValidationError{
				field:  "ScanResponse",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	for idx, item := range m.GetOcrResponses() {
		_, _ = idx, item

		if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return InternalScanResponseValidationError{
					field:  fmt.Sprintf("OcrResponses[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	return nil
}

// InternalScanResponseValidationError is the validation error returned by
// InternalScanResponse.Validate if the designated constraints aren't met.
type InternalScanResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e InternalScanResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e InternalScanResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e InternalScanResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e InternalScanResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e InternalScanResponseValidationError) ErrorName() string {
	return "InternalScanResponseValidationError"
}

// Error satisfies the builtin error interface
func (e InternalScanResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sInternalScanResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = InternalScanResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = InternalScanResponseValidationError{}
